name: CI Pipeline

on:
  push:
    branches:
      - docker_ci

jobs:
  build_and_test_container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install scikit-learn joblib

      - name: Run training script
        run: |
          python src/train.py

      - name: Build Docker image
        run: |
          docker build -t housing-model:latest .

      - name: Run container
        run: |
          docker run --rm housing-model:latest

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag & Push image
        run: |
          docker tag housing-model:latest ${{ secrets.DOCKER_USERNAME }}/housing-model:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/housing-model:latest
